/**
 * Output seam: open a pull request from a finished run.
 *
 * The PR body is built from the run summary + per-item records and links the
 * originating issue ("Closes #N"). Branch creation/commit/push is git.ts; this
 * module is the GitHub API call, behind the GitHubClient interface so it is
 * testable with a fake.
 */
import type { FinalRecord } from "../contracts.js";
import type { RunSummary } from "../metrics.js";
import type { GitHubClient, PullData } from "./client.js";

export function renderPullBody(
  summary: RunSummary,
  records: FinalRecord[],
  issueNumber: number | null,
): string {
  const rows = [...records]
    .sort((a, b) => a.workItem.id.localeCompare(b.workItem.id))
    .map((r) => `| ${r.workItem.id} | ${r.workItem.title} | ${r.passed ? "✅" : "❌"} | ${r.attempts} |`);

  return [
    issueNumber !== null ? `Closes #${issueNumber}\n` : "",
    "## Summary",
    `Generated by the agent pipeline: **${summary.passed}/${summary.total}** items passed`,
    summary.reworks > 0 ? ` (${summary.reworks} reworks).` : ".",
    "",
    "| Item | Title | Result | Attempts |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
    "🤖 Generated with the agent pipeline.",
  ].join("\n");
}

export interface OpenPullArgs {
  owner: string;
  repo: string;
  title: string;
  head: string; // branch with the changes
  base: string; // target branch
  summary: RunSummary;
  records: FinalRecord[];
  issueNumber: number | null;
}

export async function openPullRequest(client: GitHubClient, args: OpenPullArgs): Promise<PullData> {
  const body = renderPullBody(args.summary, args.records, args.issueNumber);
  return client.createPull({
    owner: args.owner,
    repo: args.repo,
    title: args.title,
    head: args.head,
    base: args.base,
    body,
  });
}
